title: Mahedi Hasan Nabil's Blog
description: > # this means to ignore newlines until "baseurl:"
   Welcome to my blog site, where I share my thoughts and insights on various topics related to technology, business, and lots of other things.Through this blog site, I hope to share my knowledge and experience with you, as well as learn from your feedback and comments.

permalink: ':title/'
image: "https://mhnabilcoder.github.io/blog/assets/img/preview.png"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mhnabilcoder.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mahedi Hasan Nabil # add your name
author-img: passport.jpeg # add your photo
about-author: Thanks for reading.. if you are interested to know more please visit my website # add description
social-website: mhnabilcoder.github.io/ # add your Twitter handle
social-facebook: mahedi.hasan.nabil # add your Facebook handle
social-github: mhnabilcoder # add your Github handle
social-linkedin: mahedi-hasan-nabil # add your Linkedin handle
social-email: mhnabilcoder@gmail.com # add your Email address

# Disqus
disqus:
 shortname: https-mhnabilcoder-github-io
 
defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        comments: true   # change to false to default to comments off site-wide
        
        


# Tracker
analytics:  # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
