title: Mahedi Hasan Nabil's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mhnabilcoder.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mahedi Hasan Nabil # add your name
author-img: passport.jpeg # add your photo
about-author: Thanks for reading.. if you are interested to know more please visit my website # add description
social-website: mhnabilcoder.github.io/ # add your Twitter handle
social-facebook: mahedi.hasan.nabil # add your Facebook handle
social-github: mhnabilcoder # add your Github handle
social-linkedin: mahedi-hasan-nabil # add your Linkedin handle
social-email: mhnabilcoder@gmail.com # add your Email address

# Disqus
discus-identifier: https://https-mhnabilcoder-github-io  # add your discus identifier
comments: true


# Tracker
analytics:  # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
